### ISSUE TITLE
Visualizar códigos de professor e do aluno

### ISSUE THREAD

**Issue by barretoMarcosPaulo** [barretoMarcosPaulo/educa-online-web#9]
Criar uma página na dashboard da escola onde é possível ver os dois códigos que foram gerados, para professor e para o aluno.

**Comment by diegofsousa** [comment]
Fala, Marcão! Posso trabalhar nessa :)

Pode ser uma TemplateView na app school? Pensei em fazer um modal simples no index do dashboard, só que não sei se é interessante jogar a query nessa view.

```python
class Index(TemplateView):
    template_name = "index.html"
```

Então, seguindo o design atual, seria uma view na app scholl mesmo. Assim como ListTeachersSchool e ListAddSubjects.

**Comment by barretoMarcosPaulo** [comment]
Opa fera!! Mano gostei da ideia do modal, ia ficar bem show. Acho que não tem problema mandar nessa view não
